
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Nov 11 2025 02:08:10 EST (Nov 11 2025 07:08:10 UTC)

// Verification Directory fv/shift_register_siso_sipo 

module shift_register_siso_sipo(clk, reset, data_in, data_out,
     parallel_out);
  input clk, reset, data_in;
  output data_out;
  output [3:0] parallel_out;
  wire clk, reset, data_in;
  wire data_out;
  wire [3:0] parallel_out;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, n_4;
  assign parallel_out[3] = data_out;
  DFFTRXL \shift_reg_reg[3] (.CK (clk), .D (n_4), .RN
       (parallel_out[2]), .Q (data_out), .QN (UNCONNECTED));
  DFFTRXL \shift_reg_reg[2] (.CK (clk), .D (parallel_out[1]), .RN
       (n_4), .Q (parallel_out[2]), .QN (UNCONNECTED0));
  DFFTRXL \shift_reg_reg[1] (.CK (clk), .D (parallel_out[0]), .RN
       (n_4), .Q (parallel_out[1]), .QN (UNCONNECTED1));
  DFFTRX1 \shift_reg_reg[0] (.CK (clk), .D (n_4), .RN (data_in), .Q
       (parallel_out[0]), .QN (UNCONNECTED2));
  INVXL g93(.A (reset), .Y (n_4));
endmodule

