/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID cad18)
#  Generated on:      Tue Nov 11 03:16:55 2025
#  Design:            shift_register_siso_sipo
#  Command:           saveNetlist shift_register_siso_sipo.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Nov 11 2025 02:08:10 EST (Nov 11 2025 07:08:10 UTC)
// Verification Directory fv/shift_register_siso_sipo 
module shift_register_siso_sipo (
	clk, 
	reset, 
	data_in, 
	data_out, 
	parallel_out);
   input clk;
   input reset;
   input data_in;
   output data_out;
   output [3:0] parallel_out;

   // Internal wires
   wire FE_PHN2_parallel_out_1;
   wire FE_PHN1_data_in;
   wire FE_PHN0_reset;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire n_4;

   assign parallel_out[3] = data_out ;

   DLY2X1 FE_PHC2_parallel_out_1 (.A(parallel_out[1]),
	.Y(FE_PHN2_parallel_out_1));
   DLY1X1 FE_PHC1_data_in (.A(data_in),
	.Y(FE_PHN1_data_in));
   DLY1X1 FE_PHC0_reset (.A(reset),
	.Y(FE_PHN0_reset));
   DFFTRXL \shift_reg_reg[3]  (.CK(clk),
	.D(n_4),
	.Q(data_out),
	.QN(UNCONNECTED),
	.RN(parallel_out[2]));
   DFFTRXL \shift_reg_reg[2]  (.CK(clk),
	.D(FE_PHN2_parallel_out_1),
	.Q(parallel_out[2]),
	.QN(UNCONNECTED0),
	.RN(n_4));
   DFFTRXL \shift_reg_reg[1]  (.CK(clk),
	.D(parallel_out[0]),
	.Q(parallel_out[1]),
	.QN(UNCONNECTED1),
	.RN(n_4));
   DFFTRXL \shift_reg_reg[0]  (.CK(clk),
	.D(n_4),
	.Q(parallel_out[0]),
	.QN(UNCONNECTED2),
	.RN(FE_PHN1_data_in));
   INVXL g93 (.A(FE_PHN0_reset),
	.Y(n_4));
endmodule

